#include <iostream>
#include <iomanip>
using namespace std;
int main ()
{
    int volunteers_num, total_boxes_sold, boxes_sold, avg_boxes_sold;
    float profit, revenue;
    string name;

    const string SENTINAL = "-1";

    cout<<fixed<<showpoint<<setprecision(2);
    
    total_boxes_sold  = 0;
    volunteers_num = 0;

    while(name != SENTINAL)
    {
        cout<<"Enter the name of volunteer and the number of boxes he has sold: "<<endl;
        cin>>name>>boxes_sold;

        total_boxes_sold = total_boxes_sold + boxes_sold;

        volunteers_num++;
    }

    cout<<"Total number of cookie boxes sold: "<<total_boxes_sold<<endl;

    cout<<"Enter the profit per box: ";
    cin>>profit;

    revenue = profit * total_boxes_sold;

    cout<<"The total revenue generated by selling cookie boxes = "<<revenue<<endl;

    cout<<"The total number of volunteers = "<<volunteers_num<<endl;

    if (volunteers_num != 0)
    {
        avg_boxes_sold = total_boxes_sold / volunteers_num;

        cout<<"The average number of boxes sold by each volunteer = "<<avg_boxes_sold<<endl;
    }
    else 
    {
        cout<<"No Volunteers."<<endl;
    }

    return 0;
}